--PESQUISAS DADOS
SELECT * FROM PRODUTO

--TABELA TEMPORARIA
ALTER PROCEDURE SP_TABELA_TEMPORARIA
AS
--TABELA FISICA
IF NOT EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME='PESQUISA_FISICA')
CREATE TABLE PESQUISA_FISICA 
(SIGLA VARCHAR(2) NULL,
ESTADO VARCHAR(30) NULL,
CIDADE VARCHAR(30) NULL)
--INCLUSAO DE DADOS
INSERT INTO PESQUISA_FISICA
SELECT DS_SIGLA,NM_ESTADO,NM_CIDADE FROM ESTADO AS E
INNER JOIN CIDADE AS C ON E.CD_ESTADO=C.CD_ESTADO
ORDER BY DS_SIGLA,NM_CIDADE
--TABELA TEMPORARIA CREATE --(# <--- CRIA A TABELA TEMPORARIA)
CREATE TABLE #PESQUISA_TEMPORARIA  
(SIGLA  VARCHAR(2) NULL,
ESTADO VARCHAR (30)NULL,
CIDADE VARCHAR (30) NULL)
--INCLUSAO DE DADOS
INSERT INTO  #PESQUISA_TEMPORARIA
SELECT DS_SIGLA,NM_ESTADO,NM_CIDADE FROM ESTADO AS E
INNER JOIN CIDADE AS C ON E.CD_ESTADO=C.CD_ESTADO

--PESQUISAR
SELECT * FROM PESQUISA_FISICA
SELECT * FROM #PESQUISA_TEMPORARIA 
 
 EXECUTE SP_TABELA_TEMPORARIA

 