--PESQUISA
SELECT * FROM CIDADE
SELECT * FROM ESTADO

--UNIR TABELAS
SELECT COUNT(*) AS 'QTDE'
FROM ESTADO AS E
INNER JOIN CIDADE AS C ON E.CD_ESTADO = C.CD_ESTADO
ORDER BY DS_SIGLA, NM_CIDADE

--CONTAR AS CIDADES
SELECT COUNT(*) AS 'QTDE'
FROM ESTADO AS E
INNER JOIN CIDADE AS C ON E.CD_ESTADO = C.CD_ESTADO
WHERE DS_SIGLA = 'SP'

--COLOCAR A SIGLA E NOME DO ESTADO
--ERRO DE GROUP BR
SELECT DS_SIGLA, NM_ESTADO, COUNT(*) AS 'QTDE'
FROM ESTADO AS E
INNER JOIN CIDADE AS C ON E.CD_ESTADO = C.CD_ESTADO

--USANDO O GROUP BY E ORDER BY 
SELECT DS_SIGLA, NM_ESTADO, COUNT(*) AS 'QTDE'
FROM ESTADO AS E
INNER JOIN CIDADE AS C ON E.CD_ESTADO = C.CD_ESTADO
GROUP BY DS_SIGLA, NM_ESTADO
ORDER BY DS_SIGLA

--TABELA SYSOBJECTS
SELECT * FROM SYSOBJECTS WHERE name = 'CARGO'

--VERIFICAR SE A TABELA QTDE_CIDADE EXISTE
SELECT * FROM SYSOBJECTS WHERE name = 'QTDE_CIDADE'

--USAR O IF EXISTS PARA VERIFICAR SE A TABELA EXISTE
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE name = 'QTDE_CIDADE')
    SELECT 'JÁ CADASTRADA ELIMINAR OS DADOS!!'
ELSE 
    SELECT 'CRIAR TABELA'