-- PESQUISA
SELECT * FROM QTDE_CIDADE

-- INCLUIR UMA CIDADE NOVA
INSERT INTO CIDADE (NM_CIDADE) VALUES ('ITU')

-- PESQUISA
SELECT * FROM CIDADE ORDER BY NM_CIDADE

-- PESQUISA
SELECT * FROM QTDE_CIDADE

-- EXECUTAR PROCEDIMENTO ARMAZENADO
EXECUTE SP_CARGA_CIDADE

-- CRIAR TRIGGER PARA SOMAR NA QTDE DE CIDADES
CREATE TRIGGER TR_INCLUIR_CIDADE
ON CIDADE
FOR INSERT 
AS
BEGIN
    -- A TABELA TEMPORÁRIA INSERTED VAI TER OS DADOS
    -- DA INCLUSÃO DA CIDADE
    DECLARE @CIDADE VARCHAR(30), @SIGLA VARCHAR(2)
    DECLARE @CD_ESTADO INT
    
    SELECT @CIDADE = NM_CIDADE FROM inserted 
    SELECT @CD_ESTADO = CD_ESTADO FROM CIDADE WHERE NM_CIDADE = @CIDADE
    SELECT @SIGLA = DS_SIGLA FROM ESTADO WHERE CD_ESTADO = @CD_ESTADO
    
    UPDATE QTDE_CIDADE SET QTDE = QTDE + 1 WHERE SIGLA = @SIGLA
END;

-- INSERIR CIDADE COM VALOR DE QTDE
INSERT INTO CIDADE VALUES ('ITACARÉ', 23)

-- PESQUISA
SELECT * FROM CIDADE;