-- CRIAR A PROCEDURE DE CARGA DE DADOS NA TABELA QTDE_CIDADE
CREATE PROCEDURE SP_CARAGA_CIDADE
AS
BEGIN
    IF OBJECT_ID('QTDE_CIDADE', 'U') IS NOT NULL
    BEGIN
        TRUNCATE TABLE QTDE_CIDADE;
    END
    ELSE
    BEGIN
        CREATE TABLE QTDE_CIDADE
        (
            CD_QTDE INT IDENTITY (1,1) NOT NULL,
            SIGLA VARCHAR(2) NULL,
            ESTADO VARCHAR(30) NULL,
            QTDE INT NULL
            CONSTRAINT PK_QTDE_CIDADE PRIMARY KEY (CD_QTDE)
        );
    END
    
    -- INCLUIR DADOS
    INSERT INTO QTDE_CIDADE
    SELECT DS_SIGLA, NM_ESTADO, COUNT(*) AS 'QTDE'
    FROM ESTADO AS E
    INNER JOIN CIDADE AS C ON E.CD_ESTADO = C.CD_ESTADO
    GROUP BY DS_SIGLA, NM_ESTADO;
END

EXEC SP_CARAGA_CIDADE;

SELECT * FROM QTDE_CIDADE