--PESQUISA 
INSERT INTO ESTADO  VALUES ('Rio de Janeiro','RJ');
INSERT INTO ESTADO  VALUES ('Minas Gerais','MG');
INSERT INTO ESTADO  VALUES ('Bahia','BA');
INSERT INTO ESTADO  VALUES ('Rio Grande do Sul','RS');
INSERT INTO ESTADO  VALUES ('Ceará','CE');

--PESQUISA DE ESTADO
SELECT * FROM cidade

--INCLUIR CIDADE
INSERT INTO CIDADE VALUES ('Paraná',2);
INSERT INTO CIDADE VALUES ('São Paulo',1);
INSERT INTO CIDADE VALUES ('Rio de Janeiro',5);
INSERT INTO CIDADE VALUES ('Minas Gerais',7);
INSERT INTO CIDADE VALUES ('Bahia',8);
INSERT INTO CIDADE VALUES ('Rio Grande do Sul',9);
INSERT INTO CIDADE VALUES ('Ceará',10);

DELETE FROM CIDADE WHERE NM_CIDADE = 'Ceará';

--UNIR TABELAS SEM A CONDIÇÃO PK
SELECT * FROM ESTADO,CIDADE
--PLANO CARTESIANO VOLUME DE DADOS
SELECT * FROM ESTADO,CIDADE
--ATE OS ANOS 2000 USAVAMOS A CONDIÇÃO A BAIXO
SELECT * FROM ESTADO,CIDADE
WHERE CD_ESTADO=CD_ESTADO 
--COM APELIDOS
SELECT * FROM ESTADO AS E, CIDADE AS C
WHERE E.CD_ESTADO=C.CD_ESTADO 