		--CADASTRO DEPARTAMENTO--
INSERT INTO DEP VALUES ('DEPARTAMENTO DE RECURSOS HUMANOS')
INSERT INTO DEP VALUES ('DEPARTAMENTO FINANCEIRO')
INSERT INTO DEP VALUES ('DEPARTAMENTO DE VENDAS')
INSERT INTO DEP VALUES ('DEPARTAMENTO DE MARKETING')
		
		--PROCEDURE--
CREATE PROCEDURE SP_INCLUI_DEP
@DEP VARCHAR(30)
AS
SELECT CD_DEP,NM_DEP FROM DEP
INSERT INTO DEP(NM_DEP)VALUES(@DEP)

		--PRODUCE ALIMENTAR OS DEP--
CREATE PROCEDURE SP_INCLUI_DEP
@DEP VARCHAR(30)
AS
INSERT INTO DEP VALUES (@DEP)

		--PROCEDURE PARA PESQUISAR DEP--
CREATE PROCEDURE SP_PESQUISA_DEP
AS 
SELECT NM_DEP FROM DEP ORDER BY NM_DEP 

		--EXECUTAR--
EXECUTE SP_INCLUI_DEP 'DEPARTAMENTO DE RECURSOS HUMANOS'
EXECUTE SP_PESQUISA_DEP

SELECT * FROM DEP