--PROCEDURE PARA ALIMENTAR OS ESTADOS
CREATE PROCEDURE SP_INCLUI_ESTADO
@SIGLA VARCHAR(2),@ESTADO VARCHAR(30)
AS
INSERT INTO ESTADO VALUES (@ESTADO,@SIGLA)
--PROCEDURE PARA PESQUISAR OS ESTADOS
ALTER PROCEDURE SP_PESQUISA_ESTADO
AS
SELECT DS_SIGLA,NM_ESTADO FROM ESTADO ORDER BY NM_ESTADO
--EXECUTAR
EXECUTE SP_INCLUI_ESTADO 'SP','SÃO PAULO'
EXECUTE SP_PESQUISA_ESTADO
--EXECUTAR
EXECUTE SP_INCLUI_ESTADO 'PR','PARANÁ'
EXECUTE SP_PESQUISA_ESTADO
