		--CADASTRO DEPARTAMENTO--
INSERT INTO DEP VALUES ('DEPARTAMENTO DE RECURSOS HUMANOS')
INSERT INTO DEP VALUES ('DEPARTAMENTO FINANCEIRO')
INSERT INTO DEP VALUES ('DEPARTAMENTO DE VENDAS')
INSERT INTO DEP VALUES ('DEPARTAMENTO DE MARKETING')
		
		--PROCEDURE--
CREATE PROCEDURE SP_INCLUI_DEP
@DEP VARCHAR(30)
AS
SELECT CD_DEP,NM_DEP FROM DEP
INSERT INTO DEP('DEPARTAMENTO DE RECURSOS HUMANOS') VALUES(@DEP)

		--EXECUTAR--
EXECUTE SP_INCLUI_DEP 'DEPARTAMENTO DE RECURSOS HUMANOS'


SELECT * FROM DEP