-- Criar tabela ESTADO caso não exista
    CREATE TABLE ESTADO
    (
        [DS_SIGLA] VARCHAR(2),
        [NM_ESTADO] VARCHAR(30)
    )
END
GO

-- Criar procedure SP_INCLUI_ESTADO
CREATE PROCEDURE SP_INCLUI_ESTADO
    @SIGLA VARCHAR(2),
    @ESTADO VARCHAR(30)
AS
BEGIN
    INSERT INTO ESTADO VALUES (@SIGLA, @ESTADO);
END
GO

-- Criar procedure SP_PESQUISA_ESTADO
CREATE PROCEDURE SP_PESQUISA_ESTADO
AS
BEGIN
    SELECT DS_SIGLA, NM_ESTADO FROM ESTADO ORDER BY NM_ESTADO;
END
GO

-- Executar SP_INCLUI_ESTADO
EXEC SP_INCLUI_ESTADO 'SP', 'SÃO PAULO';

-- Executar SP_PESQUISA_ESTADO
EXEC SP_PESQUISA_ESTADO;

-- Executar SP_INCLUI_ESTADO novamente
EXEC SP_INCLUI_ESTADO 'PR', 'PARANÁ';

-- Executar SP_PESQUISA_ESTADO novamente
EXEC SP_PESQUISA_ESTADO;