--CADASTRO BAIRROS

CREATE PROCEDURE SP_INCLUI_BAIRRO
@BAIRRO VARCHAR(30)
AS
INSERT INTO BAIRRO VALUES(@BAIRRO)

CREATE PROCEDURE SP_PESQUISA_BAIRRO
AS
SELECT NM_BAIRRO FROM BAIRRO ORDER BY NM_BAIRRO

EXECUTE SP_INCLUI_BAIRRO 'LIBERDADE'
EXECUTE SP_PESQUISA_BAIRRO 

EXECUTE SP_INCLUI_BAIRRO 'PARAISO'
EXECUTE SP_PESQUISA_BAIRRO

