		--CADASTRO CARGO
INSERT INTO CARGO VALUES ('ANALISTA DE SISTEMAS')
INSERT INTO CARGO VALUES ('DESENVOLVEDOR WEB')

		--PESQUISA DE CARGOS (MENOS PERFOMANCE)--
SELECT * FROM CARGO

		--PESQUISA COM MAIS PERFORMANCE--
SELECT	 CD_CARGO,NM_CARGO FROM CARGO
ORDER BY NM_CARGO	

		--CRIAR UMA PROCEDURE--
CREATE PROCEDURE SP_PESQUISA_CARGO
AS 
SELECT	 CD_CARGO,NM_CARGO FROM CARGO
ORDER BY NM_CARGO	

		--EXECUTAR A PROCEDURE--
EXECUTE	SP_PESQUISA_CARGO 
EXEC	SP_PESQUISA_CARGO
		SP_PESQUISA_CARGO

		--DEFINIR VARIAVEL DE MEMORIA
DECLARE @VALOR INT = 121
DECLARE @VALOR

		--VARIAVEL COM TEXTO
DECLARE @VALOR INT = 121
DECLARE @NOME VARCHAR  (30)
SELECT  @VALOR,@NOME

		--ALTERAR AS VARIAVEIS DE MEMORIA--
DECLARE @VALOR INT = 121
DECLARE @NOME VARCHAR  (30)
SELECT  @VALOR,@NOME
SET		@VALOR =144
SET		@NOME =  'JULIA'
SELECT	@VALOR,@NOME

		--SEPARAR POR TIPO DE DADOS
DECLARE @VALOR INT = 121, @IDADE INT
DECLARE @NOME VARCHAR  (30), @CEP VARCHAR(8)
SELECT  @VALOR,@NOME,@IDADE,@CEP
SET		@VALOR =144
SET		@IDADE =30
SET		@CEP =09999000
SET		@NOME =  'JULIA'
SELECT	@VALOR,@NOME,@IDADE,@CEP

		--USAR SELECT PARA ALIMENTAR A VARIAVEL @CARGO
SELECT  *FROM CARGO WHERE CD_CARGO = 1

		--APRESENTAR O NOME DO CARGO
SELECT  NM_CARGO FROM CARGO WHERE CD_CARGO = 1

		--CRIAR A VARIAVEL PARA RECEBER CARGO
DECLARE @CARGO VARCHAR(30)
SELECT	@CARGO=NM_CARGO FROM CARGO WHERE CD_CARGO = 1
SELECT	@CARGO 

		--CRIAR UMA PROCEDURE PARA PESQUISAR QUALQUER--

		--CARGO USANDO PK--
EXECUTE SP_PESQUISA_CARGO
--
CREATE  PROCEDURE SP_PESQUISA_CARGO_PK 
@CARGO  INT
AS 
SELECT  NM_CARGO FROM CARGO WHERE CD_CARGO = @CARGO
--
EXECUTE SP_PESQUISA_CARGO_PK @CARGO = 1

		--PROCEDURE PARA ALIMENTAR--
CREATE  PROCEDURE SP_INCLUI_CARGO
@CARGO  VARCHAR(30)
AS
INSERT  INTO CARGO VALUES (@CARGO)
		--EXECUTAR--
EXECUTE SP_INCLUI_CARGO 'ANALISTA DE TESTES'
EXECUTE SP_PESQUISA_CARGO 
		--EXECUTAR--
EXECUTE SP_INCLUI_CARGO 'PMI'
EXECUTE SP_PESQUISA_CARGO

