--PESQUISA 
SELECT DS_SIGLA,NM_ESTADO,NM_CIDADE FROM ESTADO AS E
INNER JOIN CIDADE AS C ON E.CD_ESTADO=C.CD_ESTADO
--USADO EM OUTRO B.D 
SELECT * FROM LOJA1
SELECT NM_PRODUTO, DT_COMPRA, YEAR(DT_COMPRA)
FROM LOJA1

SELECT NM_PRODUTO, DT_COMPRA,
YEAR (DT_COMPRA) AS 'ANO', MONTH (DT_COMPRA) AS 'MÊS',
DAY(DT_COMPRA) AS 'DIA', YEAR ('03/04/2024')
FROM LOJA1


SELECT YEAR(GETDATE()) AS 'DATA E HORA DO SISTEMA'
--
SELECT COUNT(NM_PRODUTO), COUNT(*) AS 'QTDE', MIN(PC_PRODUTO) AS 'MENOR',
MAX(PC_PRODUTO) AS 'MAIOR', SUM(PC_PRODUTO) AS 'SOMA',
AVG(PC_PRODUTO) AS 'MÉDIA'
FROM LOJA1 
 ---GROUP BAR
SELECT DS_SIGLA,COUNT (*) AS 'QTDE'
FROM ESTADO AS E
INNER JOIN CIDADE AS C ON E.CD_ESTADO=C.CD_ESTADO
GROUP BY DS_SIGLA
ORDER BY COUNT(*) DESC