/* Lógico_1 ATT: */

CREATE TABLE FUNCIONARIO (
    CD_FUNC INT PRIMARY KEY,
    DT_ADMISSAO DATE,
    DS_SEXO VARCHAR(1),
    VL_SALARIO NUMERIC(18,2),
    NM_FUNC VARCHAR(50),
    DS_LOGRADOURO VARCHAR(50),
    DS_COMPLEMENTO VARCHAR(50),
    DS_CEP VARCHAR(8),
    FK_CARGO_CD_CARGO INT,
    FK_DEPARTAMENTO_CD_DEPARTAMENTO INT,
    FK_BAIRRO_CD_BAIRRO INT,
    FK_CIDADE_CD_CIDADE INT
);

CREATE TABLE CARGO (
    CD_CARGO INT PRIMARY KEY,
    NM_CARGO VARCHAR(30)
);

CREATE TABLE DEPARTAMENTO (
    NM_DEPARTAMENTO VARCHAR(30),
    CD_DEPARTAMENTO INT PRIMARY KEY
);

CREATE TABLE BAIRRO (
    CD_BAIRRO INT PRIMARY KEY,
    NM_BAIRRO VARCHAR(30)
);

CREATE TABLE CIDADE (
    CD_CIDADE INT PRIMARY KEY,
    NM_CIDADE VARCHAR(30),
    FK_ESTADO_CD_ESTADO INT
);

CREATE TABLE ESTADO (
    CD_ESTADO INT PRIMARY KEY,
    DS_SIGLA VARCHAR(2),
    NM_ESTADO VARCHAR(30)
);
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_2
    FOREIGN KEY (FK_CARGO_CD_CARGO)
    REFERENCES CARGO (CD_CARGO)
    ON DELETE RESTRICT;
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_3
    FOREIGN KEY (FK_DEPARTAMENTO_CD_DEPARTAMENTO)
    REFERENCES DEPARTAMENTO (CD_DEPARTAMENTO)
    ON DELETE RESTRICT;
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_4
    FOREIGN KEY (FK_BAIRRO_CD_BAIRRO)
    REFERENCES BAIRRO (CD_BAIRRO)
    ON DELETE RESTRICT;
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_5
    FOREIGN KEY (FK_CIDADE_CD_CIDADE)
    REFERENCES CIDADE (CD_CIDADE)
    ON DELETE RESTRICT;
 
ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_2
    FOREIGN KEY (FK_ESTADO_CD_ESTADO)
    REFERENCES ESTADO (CD_ESTADO)
    ON DELETE RESTRICT;