--FUNCIONARIOS ADD PK = FK OU FK =PK
--FUNCIONARIO E DEPARTAMENTO
SELECT NM_FUNC,DT_ADMISSAO,VL_SALARIO,DS_SEXO
FROM FUNC AS F
INNER JOIN DEP AS D ON D.CD_DEP=F.CD_DEP


----
SELECT NM_FUNC,DT_ADMISSAO,VL_SALARIO,DS_SEXO
FROM FUNC AS F
INNER JOIN DEP AS D ON D.CD_DEP=F.CD_DEP
INNER JOIN CARGO AS C ON C.CD_CARGO=F.CD_CARGO

--
SELECT NM_FUNC,DT_ADMISSAO,VL_SALARIO,DS_SEXO,NM_BAIRRO,NM_CARGO,NM_DEP,NM_CIDADE,NM_ESTADO,DS_SIGLA
FROM FUNC AS F
INNER JOIN DEP AS D ON D.CD_DEP=F.CD_DEP
INNER JOIN CARGO AS C ON C.CD_CARGO=F.CD_CARGO
INNER JOIN BAIRRO AS B ON B.CD_BAIRRO=F.CD_BAIRRO
INNER JOIN CIDADE AS CI ON CI.CD_CIDADE=F.CD_CIDADE
INNER JOIN ESTADO AS E ON E.CD_ESTADO=CI.CD_ESTADO 

--CRIAR UMA VIEW PARA PESQUISAR
CREATE VIEW VW_GERAL
AS
SELECT NM_FUNC,DT_ADMISSAO,VL_SALARIO,DS_SEXO,NM_BAIRRO,NM_CARGO,NM_DEP,NM_CIDADE,NM_ESTADO,DS_SIGLA
FROM FUNC AS F
INNER JOIN DEP AS D ON D.CD_DEP=F.CD_DEP
INNER JOIN CARGO AS C ON C.CD_CARGO=F.CD_CARGO
INNER JOIN BAIRRO AS B ON B.CD_BAIRRO=F.CD_BAIRRO
INNER JOIN CIDADE AS CI ON CI.CD_CIDADE=F.CD_CIDADE
INNER JOIN ESTADO AS E ON E.CD_ESTADO=CI.CD_ESTADO 
--USANDO VIEW
SELECT * FROM VW_GERAL
--CRIAR UMA PROCEDURE PARA USAR A VIEW
CREATE PROCEDURE SP_GERAL
AS
SELECT * FROM VW_GERAL

SP_GERAL
