--CRIAR O BANCO DE DADOS
CREATE DATABASE FMU_RH_Yuri;
--COLOCAR O BANCO EM USO
	USE FMU_RH_Yuri
--CRIAÇÃO DAS TABELAS

		--TABELA CARGO--
CREATE TABLE CARGO
(CD_CARGO INT IDENTITY(1,1) NOT NULL ,
NM_CARGO VARCHAR(30) NOT NULL,
CONSTRAINT PK_CARGO PRIMARY KEY(CD_CARGO),
CONSTRAINT UNICO_CARGO UNIQUE(NM_CARGO))

		--TABELA DEPARTAMENTO--
CREATE TABLE DEP
(CD_DEP INT IDENTITY(1,1) NOT NULL,
NM_DEP VARCHAR(30) NOT NULL,
CONSTRAINT PK_DEP PRIMARY KEY(CD_DEP),
CONSTRAINT UNICO_DEP UNIQUE(NM_DEP))

		-- TABELA BAIRRO--
CREATE TABLE BAIRRO
(CD_BAIRRO INT IDENTITY (1,1) NOT NULL,
NM_BAIRRO VARCHAR(30) NOT NULL,
CONSTRAINT PK_BAIRRO PRIMARY KEY (CD_BAIRRO))

		--TABELA ESTADO--
CREATE TABLE ESTADO
(CD_ESTADO INT IDENTITY (1,1) NOT NULL,
NM_ESTADO VARCHAR(30) NOT NULL,
DS_SIGLA VARCHAR(2) NOT NULL,
CONSTRAINT PK_ESTADO PRIMARY KEY(CD_ESTADO),
CONSTRAINT UNICO_SIGLA UNIQUE (DS_SIGLA),
CONSTRAINT UNICO_ESTADO UNIQUE(NM_ESTADO))

		--TABELA CIDADE--
CREATE TABLE CIDADE
(CD_CIDADE INT IDENTITY (1,1) NOT NULL,
NM_CIDADE VARCHAR(30) NOT NULL,
CD_ESTADO INT NOT NULL,
CONSTRAINT PK_CIDADE PRIMARY KEY (CD_CIDADE),
CONSTRAINT FK_CIDADE FOREIGN KEY (CD_ESTADO) REFERENCES ESTADO (CD_ESTADO))

		--TABELA FUNCIONARIO--
CREATE TABLE FUNC
(CD_FUNC INT IDENTITY (1,1) NOT NULL,
NM_FUNC VARCHAR(50) NOT NULL,
DT_ADMISSAO DATE NOT NULL,
VL_SALARIO DECIMAL(18,2) NOT NULL,
DS_SEXO VARCHAR(2) NOT NULL,
DS_LOGRADOURO VARCHAR(50) NOT NULL,
DS_COMPLEMENTO VARCHAR(50) NOT NULL,
DS_CEP VARCHAR(8),
CD_CARGO INT NOT NULL,
CD_DEP INT NOT NULL,
CD_BAIRRO INT NOT NULL,
CD_CIDADE INT NOT NULL,
CONSTRAINT PK_FUNC PRIMARY KEY(CD_FUNC),
CONSTRAINT FK_FUN_CARGO FOREIGN KEY (CD_CARGO) REFERENCES CARGO(CD_CARGO),
CONSTRAINT FK_FUN_DEP FOREIGN KEY (CD_DEP) REFERENCES DEP(CD_DEP),
CONSTRAINT FK_FUN_BAIRRO FOREIGN KEY (CD_BAIRRO) REFERENCES BAIRRO(CD_BAIRRO),
CONSTRAINT FK_FUN_CIDADE FOREIGN KEY (CD_CIDADE) REFERENCES CIDADE(CD_CIDADE),
CONSTRAINT CHEQUE_SEXO CHECK(DS_SEXO IN('F','M')))
--------

USE FMU_RH;
SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';






