--TABELA NO MASTER
SELECT * FROM SYSOBJECTS
--PESQUISAR OS OBEJTOS CRIADOS PELO USER
SELECT * FROM  SYSOBJECTS WHERE xtype ='U'
--PESQUISAR A TABELA PESQUISA_FISICA
SELECT * FROM  SYSOBJECTS WHERE NAME ='PESQUISA_FISICA'
--VERIFICAR SE EXISTE A TABELA PESQUISA_FISICA
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME='PESQUISA_FISICA')
SELECT 'JA CRIADA'
ELSE
SELECT 'NAO CRIADA'